"""Markdown output sized for a PR comment: a compact top-N table."""

from __future__ import annotations

from html import escape

from flakemap.stats.analyze import AnalysisResult, TestStats

_BADGE = {
    "broken": "🔴 broken",
    "flaky": "🟡 flaky",
    "healthy": "🟢 healthy",
    "insufficient_data": "⚪ n/a",
}


def _safe(text: str) -> str:
    return (
        escape(text)
        .replace("|", "&#124;")
        .replace("`", "&#96;")
        .replace("\n", " ")
        .replace("\r", " ")
    )


def _row(t: TestStats) -> str:
    ci = f"{t.failure_rate.low:.0%}–{t.failure_rate.high:.0%}"
    flip = f"{t.flip_rate:.0%}" if t.flip_pairs else "n/a"
    since = f" since <code>{_safe(t.change_point_run_id)}</code>" if t.change_point_run_id else ""
    return (
        f"| <code>{_safe(t.full_name)}</code> | {_BADGE[t.classification]} | {t.flakiness_score:.2f} "
        f"| {t.failure_rate.point:.0%} ({ci}) | {t.recovered_runs} | {flip} | {t.n}{since} |"
    )


def render_markdown(result: AnalysisResult, top_n: int = 15) -> str:
    lines = ["# flakemap report", ""]
    lines.append(
        f"{result.total_runs} runs analyzed, {len(result.tests)} tests seen. "
        f"{sum(1 for t in result.tests if t.classification == 'flaky')} flaky, "
        f"{sum(1 for t in result.tests if t.classification == 'broken')} broken."
    )
    lines.append(
        f"{sum(t.recovered_runs for t in result.tests)} test-runs passed on retry; "
        f"{sum(t.n_unknown for t in result.tests)} ambiguous test-runs excluded."
    )
    for warning in result.warnings:
        lines.append(f"\n> Warning: {_safe(warning)}")
    lines.append("")

    notable = [t for t in result.tests if t.classification in ("flaky", "broken")][:top_n]
    if not notable:
        lines.append("No flaky or broken tests detected in this window.")
        return "\n".join(lines) + "\n"

    lines.append(
        "| Test | Status | Score | Final failure rate (95% CI) | Recovered | Flip rate | Runs |"
    )
    lines.append("|---|---|---|---|---|---|---|")
    for t in notable:
        lines.append(_row(t))
    lines.append("")
    lines.append(
        "*Recovered counts runs that passed after explicit failed attempts. "
        "Score = confidence-weighted blend of flip rate, retry/same-context rerun evidence, "
        "and intermittency; see the README's formula section. "
        "Generated by [flakemap](https://github.com/antonsoo/flakemap).*"
    )
    return "\n".join(lines) + "\n"
