"""Markdown output sized for a PR comment: a compact top-N table."""

from __future__ import annotations

from flakemap.stats.analyze import AnalysisResult, TestStats

_BADGE = {
    "broken": "🔴 broken",
    "flaky": "🟡 flaky",
    "healthy": "🟢 healthy",
    "insufficient_data": "⚪ n/a",
}


def _row(t: TestStats) -> str:
    ci = f"{t.failure_rate.low:.0%}–{t.failure_rate.high:.0%}"
    since = f" since `{t.change_point_run_id}`" if t.change_point_run_id else ""
    return (
        f"| `{t.full_name}` | {_BADGE[t.classification]} | {t.flakiness_score:.2f} "
        f"| {t.failure_rate.point:.0%} ({ci}) | {t.flip_rate:.0%} | {t.n}{since} |"
    )


def render_markdown(result: AnalysisResult, top_n: int = 15) -> str:
    lines = ["# flakemap report", ""]
    lines.append(
        f"{result.total_runs} runs analyzed, {len(result.tests)} tests seen. "
        f"{sum(1 for t in result.tests if t.classification == 'flaky')} flaky, "
        f"{sum(1 for t in result.tests if t.classification == 'broken')} broken."
    )
    if result.mtime_fallback_warning:
        lines.append(f"\n> ⚠️ {result.mtime_fallback_warning}")
    lines.append("")

    notable = [t for t in result.tests if t.classification in ("flaky", "broken")][:top_n]
    if not notable:
        lines.append("No flaky or broken tests detected in this window.")
        return "\n".join(lines) + "\n"

    lines.append("| Test | Status | Score | Failure rate (95% CI) | Flip rate | Runs |")
    lines.append("|---|---|---|---|---|---|")
    for t in notable:
        lines.append(_row(t))
    lines.append("")
    lines.append(
        "*Score = confidence-weighted blend of flip rate, same-commit rerun disagreement, "
        "and intermittency; see the README's formula section. "
        "Generated by [flakemap](https://github.com/antonsoo/flakemap).*"
    )
    return "\n".join(lines) + "\n"
